### ISSUE TITLE
Executable doesn't exist - chromium_headless_shell

### ISSUE THREAD

**Issue by raphiz** [pietdevries94/playwright-web-flake#11]
I upgraded a project to `1.49.1` (which is the latest version as I'm writing) and Playwright now fails with the following error:

```
browserType.launch: Executable doesn't exist at /nix/store/s7kyjcq3mxaz9shv756zigid0l712yy0-playwright-browsers-chromium/chromium_headless_shell-1148/chrome-linux/headless_shell
```

The problem is, that the folder name has changed from `chromium-XYZ` to `chromium_headless_shell-XYZ`.

Seems to be related to https://github.com/microsoft/playwright/issues/33566

Hopefully, this is just a [rename of the folder name](https://github.com/pietdevries94/playwright-web-flake/blob/1c1971c26dc1f86b679393f1970335b7e3a768df/playwright-driver/default.nix#L133) but there might be more to it since it's a new headless mode.

**Comment by pietdevries94** [comment]
I have seen this issue yesterday too, but sadly it's a different browser and the normal version also needs to exist when not going headless. I will put in the time to figure this one out next week, and I will also pick up the other open issue.

Thanks for helping me figure this out.

Here is the issue with all the info from the playwright side of things. https://github.com/microsoft/playwright/issues/33566

**Comment by pietdevries94** [comment]
@raphiz I had some free time on my hand and have fixed the issue. The fix is pushed and released. I retagged 1.49.1, so it should work :)

Feel free to share any issues if this is not the case
