### ISSUE TITLE
v1.47.0 is shipping the wrong browser versions

### ISSUE THREAD

**Issue by UberMouse** [pietdevries94/playwright-web-flake#6]
I don't think I'm doing anything wrong here. I updated my NixOS configuration to use the new 1.47.0 variant of the flake, tried to run playwright and it said there was no browser at `/nix/store/wz21agryjd51fzqid85qx673ag3481mz-playwright-browsers-chromium/chromium-1134/chrome-linux/chrome`

Which sure enough, running `ls` on `$PLAYWRIGHT_BROWSERS_PATH` gives `chromium-1091  ffmpeg-1009`

To verify there wasn't some issue with my configuration I ran the flake using the provided nix-shell command in the README and it had the same issue, pointing at chromium-1134 but only shipping chromium-1091

**Comment by pietdevries94** [comment]
I just double checked everything and the playwright-driver.browsers is correct on the tag. However, I checked playwright-driver.browsers from 24.05 and that one downloads chromium 1091 with that exact tag. My suspicion is that you use the nixpkgs for your drivers, but without seeing your setup, it's hard to tell.

Does the example flake in README.md work for you?

**Comment by UberMouse** [comment]
Ah! That was it. I recently switched from Ubuntu/Home-manager to NixOS/Home-manager and changed from pointing nixpkgs at unstable to 24.05. Updated my NixOS flake to run the playwright flake with nixpkgs-unstable and it works. Thanks :pray:
