### ISSUE TITLE
Provide us where to discussion.

### ISSUE THREAD

**Issue by PorcoRosso85** [pietdevries94/playwright-web-flake#8]
Hi, thanks for great work.

I think this repository deserves more attention because it does not depend on node or python packages and provides functionality according to nix.

I publish the issue because of my wish.
Is it possible to have a Discussion created?
For example, my personal problem is how to use your flake for automated testing on node. The playwright package that I install with npm to solve it reads 'playwright.config.js' and selects the browser to run the tests.
https://discourse.nixos.org/t/running-playwright-tests/

I believe this issue should be independent of this package.
On the other hand, there should be a place to discuss around this repository.
Of course, I am open to the opinion that this should be done only in Discourse. I would like to hear your thoughts.

**Comment by pietdevries94** [comment]
Hmmm, I get what you're saying, but this package truly is a drop-in replacement for the nixpkgs version of this same package. I don't really mind to use the issues for questions like this for the current scale. However I enabled the discussions feature for now.

As for your problem, personally I use a devShell in my CI pipeline, with the following shellHook: 
```nix
shellHook = ''
   export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
   export PLAYWRIGHT_BROWSERS_PATH="${pkgs.playwright-driver.browsers}"
'';
```

The complete examle of a simple flake with a devShell is in the readme.
